[package]
name = "dep3"
version = "0.1.2"
edition = "2021"
license = "Apache-2.0"
description = "A library for parsing and generating DEP-3 headers."

[dependencies]
chrono = "0.4"
deb822-lossless = { path = "..", version = "0.1.6" }
